### ISSUE TITLE
Is it compatible with yi 4k plus ?

### ISSUE THREAD

**Issue by SamSpiri** [psolyca/Yi_4k_ROOTFS#2]
Can I use it with yi 4k+ camera?

**Comment by psolyca** [comment]
No I do not think.
I do not have a Yi4k+ so I did not test anything.
Firmwares are available to download but unpacking and packing are different from the Yi4k. A soft exists for that but I did not test.
BTW, drivers and somes files should be different from Yi4k on the Yi4k+.
